DROP TABLE IF EXISTS insurance;

CREATE TABLE insurance (
  id INT PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  EMAIL VARCHAR(250) NOT NULL,
  BONUS VARCHAR(250) NOT NULL,
  PERSONAL_ID VARCHAR(250) NOT NULL,
  LICENCE_PLATE VARCHAR(250) NOT NULL
);
